global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']   # Prometheus monitors itself

  - job_name: 'api'
    static_configs:
      - targets: ['api:3000']        # Your API container + port
    metrics_path: /metrics

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
