global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Load alert rules
rule_files:
  - /etc/prometheus/rules.yml

# Scrape configurations
scrape_configs:
  # Prometheus monitors itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API service metrics
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:3000']  # <-- api is the Docker service name

  # Remediator service metrics
  - job_name: 'remediator'
    metrics_path: /metrics
    static_configs:
      - targets: ['remediator:8080']  # <-- remediator is the Docker service name